import React from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, Users, Globe, DollarSign } from 'lucide-react';

const Statistics = () => {
  const stats = [
    {
      icon: Users,
      number: '1.7B',
      label: 'Unbanked People Worldwide',
      description: 'Our target market represents a massive opportunity for financial inclusion',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: DollarSign,
      number: '$50M',
      label: 'Generated by Our Users',
      description: 'Total revenue created through apps built on our platform',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: Globe,
      number: '180+',
      label: 'Countries Reached',
      description: 'Global accessibility breaking down geographical barriers',
      color: 'from-purple-500 to-pink-500'
    },
    {
      icon: TrendingUp,
      number: '300%',
      label: 'Average Revenue Growth',
      description: 'Year-over-year growth for apps built on our platform',
      color: 'from-orange-500 to-red-500'
    }
  ];

  return (
    <section id="impact" className="py-20 bg-gradient-to-br from-gray-900 via-purple-900 to-blue-900 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0">
        <div className="absolute top-20 left-10 w-72 h-72 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl opacity-10 animate-pulse"></div>
        <div className="absolute bottom-20 right-10 w-72 h-72 bg-blue-500 rounded-full mix-blend-multiply filter blur-xl opacity-10 animate-pulse"></div>
      </div>

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
            Global Impact
            <span className="block bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
              By the Numbers
            </span>
          </h2>
          <p className="text-xl text-purple-100 max-w-3xl mx-auto">
            See how we're transforming lives and creating economic opportunities for the world's unbanked population.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              whileHover={{ y: -5 }}
              className="bg-white/10 backdrop-blur-md rounded-2xl p-8 border border-white/20 hover:bg-white/15 transition-all duration-300"
            >
              <div className={`w-16 h-16 bg-gradient-to-r ${stat.color} rounded-2xl flex items-center justify-center mb-6`}>
                <stat.icon className="w-8 h-8 text-white" />
              </div>
              
              <motion.div
                initial={{ scale: 0 }}
                whileInView={{ scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 + 0.3, type: "spring" }}
                className="text-4xl lg:text-5xl font-bold text-white mb-2"
              >
                {stat.number}
              </motion.div>
              
              <h3 className="text-lg font-semibold text-purple-100 mb-3">
                {stat.label}
              </h3>
              
              <p className="text-purple-200 text-sm leading-relaxed">
                {stat.description}
              </p>
            </motion.div>
          ))}
        </div>

        {/* Additional Impact Metrics */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-20 grid md:grid-cols-3 gap-8"
        >
          <div className="text-center">
            <div className="text-3xl font-bold text-white mb-2">95%</div>
            <div className="text-purple-200">User Satisfaction Rate</div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold text-white mb-2">24/7</div>
            <div className="text-purple-200">Global Availability</div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold text-white mb-2">5 min</div>
            <div className="text-purple-200">Average Build Time</div>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default Statistics;